### ISSUE TITLE
最后点修改定位报错：An Lockdown error occurred. The error code was InvalidService。

### ISSUE THREAD

**Issue by maybehowe** [quxiaozha/JocationPlus#2]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
iMobileDevice.Lockdown.LockdownException: An Lockdown error occurred. The error code was InvalidService
   在 iMobileDevice.Lockdown.LockdownErrorExtensions.ThrowOnError(LockdownError value)
   在 LocationCleaned.LocationService.<>c__DisplayClass11_0.<UpdateLocation>b__0(DeviceModel itm) 位置 C:\Users\qiaoqiao\Desktop\JocationRelease-12.2\Jocation\LocationService.cs:行号 196
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 LocationCleaned.LocationService.UpdateLocation(Location location) 位置 C:\Users\qiaoqiao\Desktop\JocationRelease-12.2\Jocation\LocationService.cs:行号 189
   在 LocationCleaned.frmMain.button2_Click(Object sender, EventArgs e) 位置 C:\Users\qiaoqiao\Desktop\JocationRelease-12.2\Jocation\frmMain.cs:行号 143
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3394.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
JocationPlus
    程序集版本:1.6.0.0
    Win32 版本:1.6.0.0
    基本代码:file:///C:/Users/Howe/Downloads/JocationPlus_v1.6/JocationPlus.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3362.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Data.SQLite
    程序集版本:1.0.110.0
    Win32 版本:1.0.110.0
    基本代码:file:///C:/Users/Howe/Downloads/JocationPlus_v1.6/System.Data.SQLite.DLL
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3362.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Transactions
    程序集版本:4.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
iMobileDevice-net
    程序集版本:1.2.0.0
    Win32 版本:1.2.77.52199
    基本代码:file:///C:/Users/Howe/Downloads/JocationPlus_v1.6/iMobileDevice-net.DLL
----------------------------------------
System.EnterpriseServices
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.mshtml
    程序集版本:7.0.3300.0
    Win32 版本:7.0.3300.0
    基本代码:file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by quxiaozha** [comment]
win10x64、win7x64测试ok，可以检查.net版本、以及手机驱动是否加载正常。

**Comment by quxiaozha** [comment]
看下通用-设置里边有没有开发者选项，如果没有，可以通过爱思助手点工具箱-实时桌面打开。

**Comment by ChengQ001** [comment]
下载一个 爱思 之后 我的 xr完美解决了这个问题。

**Comment by quxiaozha** [comment]
Fixed

**Comment by quxiaozha** [comment]
补一个：修改时保持屏幕是解锁的状态

**Comment by chan-allen** [comment]
quxiaozha  大神，
IOS13.0驅動怎麼使用，修改位置 或者移動就報An Lockdown error occurred. The error code was InvalidService。。。請求幫助！
萬分感謝！

**Comment by ZhuHengTHU** [comment]
quxiaozha 大神，
IOS13.2驅動怎麼使用，修改位置 或者移動就報An Lockdown error occurred. The error code was InvalidService。。。請求幫助！
萬分感謝！

**Comment by ChengQ001** [comment]
首先用爱思助手先用下那个虚拟定位看是否可以，然后 在使用软件试试。或者是&nbsp; 里面 设备的版本号看是不是和你的手机版本一致
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhuHengTHU"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月30日(星期六) 下午3:39
收件人:&nbsp;"quxiaozha/JocationPlus"<JocationPlus@noreply.github.com&gt;;
抄送:&nbsp;"ChengQ"<694340776@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [quxiaozha/JocationPlus] 最后点修改定位报错：An Lockdown error occurred. The error code was InvalidService。 (#2)




quxiaozha 大神，
 IOS13.2驅動怎麼使用，修改位置 或者移動就報An Lockdown error occurred. The error code was InvalidService。。。請求幫助！
 萬分感謝！

**Comment by ChengQ001** [comment]
xr和xr以上的版本 好像都要用 爱思助手 先改下定位成功之后就可以用这个软件了。具体是什么原因 还没招到。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZhuHengTHU"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月30日(星期六) 下午3:39
收件人:&nbsp;"quxiaozha/JocationPlus"<JocationPlus@noreply.github.com&gt;;
抄送:&nbsp;"ChengQ"<694340776@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [quxiaozha/JocationPlus] 最后点修改定位报错：An Lockdown error occurred. The error code was InvalidService。 (#2)




quxiaozha 大神，
 IOS13.2驅動怎麼使用，修改位置 或者移動就報An Lockdown error occurred. The error code was InvalidService。。。請求幫助！
 萬分感謝！

**Comment by jc911** [comment]
咦，爱思助手里有这个功能，是不是就不需要这个工具了啊。。

**Comment by vlan20** [comment]
重启手机就能修改了

**Comment by CSW996** [comment]
邮件已经收到，谢谢。Your email has been received, thank you.                                                                    ——Jinfei
