### ISSUE TITLE
你好，作者，软件发生异常

### ISSUE THREAD

**Issue by nangsze** [quxiaozha/JocationPlus#3]
system.data.SQLite,version=1.0.110.0,culture=neutral,publickeytoken=db937bc2d44ff139或它的某一个依赖项。系统找不到指定的文件。情况就是软件打开后加载驱动就闪退， win 64 ，IOS12.2

**Comment by nangsze** [comment]
软件打开后加载驱动就闪退

**Comment by quxiaozha** [comment]
用的自己编译的版本还是之前的release版本

**Comment by nangsze** [comment]
用你刚刚更新的版本。




------------------ 原始邮件 ------------------
发件人: "quxiaozha"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 下午5:15
收件人: "quxiaozha/JocationPlus"<JocationPlus@noreply.github.com>; 
抄送: "ＮＡＮＧ"<165111563@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [quxiaozha/JocationPlus] 你好，作者，软件发生异常 (#3)




用的自己编译的版本还是之前的release版本

**Comment by quxiaozha** [comment]
刚刚更新的？是自己的用vs编译的么，如果是话 需要添加sqlite的依赖哈。

**Comment by nangsze** [comment]
加SQL哪里呢，新手不太懂，想学习。

**Comment by quxiaozha** [comment]
百度一下，C#使用sqlite

**Comment by ChengQ001** [comment]
xr 加载驱动之后就 异常了
