### ISSUE TITLE
C:\Program Files\dotnet\sdk\2.2.300\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: 未找到框架“.NETFramework,Versi on=v4.5”的引用程序集。若要解决此问题，请安装此框架版本的 SDK 或 Targeting Pack，或将应用程序的目标重新指向已装有 SDK 或 Targeting Pack 的框架版本。请注意，将从全局程序集缓存(GAC)解析程序集，并将使用这些程序集替换引用程序集。因此，程序集的目标可能未正确指向您所 预期的框架。 [C:\Users\Administrator\Downloads\JocationPlus-master\jocationplus\JocationPlus.csproj]  生成失败。请修复生成错误并重新运行。

### ISSUE THREAD

**Issue by zdhgithub** [quxiaozha/JocationPlus#6]
C:\Program Files\dotnet\sdk\2.2.300\Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: 未找到框架“.NETFramework,Versi
on=v4.5”的引用程序集。若要解决此问题，请安装此框架版本的 SDK 或 Targeting Pack，或将应用程序的目标重新指向已装有 SDK 或 Targeting
Pack 的框架版本。请注意，将从全局程序集缓存(GAC)解析程序集，并将使用这些程序集替换引用程序集。因此，程序集的目标可能未正确指向您所
预期的框架。 [C:\Users\Administrator\Downloads\JocationPlus-master\jocationplus\JocationPlus.csproj]

生成失败。请修复生成错误并重新运行。

我安装了.netFramework4.8报这个错，请问怎么解决呢？

**Comment by quxiaozha** [comment]
看报错是.net 4.5找不到 可以退回装4.5试试

**Comment by quxiaozha** [comment]
或者自己用源码编译一份
