### ISSUE TITLE
地图定位不能自动返回上个标记的位置

### ISSUE THREAD

**Issue by JDex623** [quxiaozha/JocationPlus#7]
修改好地图位置,再次打开不能定位到相关位置,每次都要缩小找自己位置
希望能修复一下保存地图标记位置

**Comment by quxiaozha** [comment]
加上倒是不难，但是没想好是地图里手动保存还是从主界面进去时带进去。

**Comment by JDex623** [comment]
地图进去的时候希望是定位到 已修改的坐标位置 跟location-cleaned那样

**Comment by quxiaozha** [comment]
#10
